In [6]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [15]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
#get dimension
a.ndim
b.ndim

2

In [12]:
#get shape
b.shape

(2, 3)

In [16]:
#get type
a.dtype

dtype('int16')

In [17]:
#get size
a.itemsize

2

In [18]:
#get total size
a.size

3

In [19]:
a.nbytes

6

In [20]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
a[1,-2]

13

In [23]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
#get a specific column
a[:,2]

array([ 3, 10])

In [27]:
# getting little more [ startindex:endindex:stepsize]
a[0, 1:-2:2]

array([2, 4])

In [28]:
a[1,5] = 20
print(a)
a[:,2] =5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [30]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
#get speciifc element(work outside in )
b[0,1,1]

4

In [34]:
b[:,1,0]

array([3, 7])

In [39]:
#replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Different types of Arrays

In [43]:
#All 0s matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
#all i matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [46]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [47]:
#any other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [51]:
#Random decimal numbers
np.random.random_sample(a.shape)
np.random.rand(4,2)

array([[0.06271068, 0.02862542],
       [0.1042097 , 0.41925474],
       [0.06483591, 0.39903339],
       [0.94192857, 0.67909628]])

In [62]:
#random integer values
np.random.randint(-4,7,size=(3,3))

array([[-1,  3,  2],
       [ 4,  2, -1],
       [ 5, -3, -4]])

In [64]:
#the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
arr = np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [92]:
import numpy as np
output = np.ones((5,5))
output

z1 = np.zeros((3,3))
z1[1,1] = 9
z1

output[1:4,1:4] = z1
output



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

##### Be Careful when copying Arrays!!!!

In [99]:
a=np.array([1,2,3])
b = a.copy()
b[0]=100
b
a


array([1, 2, 3])

Mathematics

In [105]:
a= np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [106]:
a + 2

array([3, 4, 5, 6])

In [107]:
a-2

array([-1,  0,  1,  2])

In [108]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [116]:
b= np.array([1,0,1,0])
a*b

array([1, 0, 3, 0])

In [110]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [113]:
#take the sin/cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#for a lot more( https://docs.scipy.org/doc/numpy/reference/routines.math.html)

#### Linear ALgebra

In [122]:
a = np.ones((2,3))
a

b= np.full((3,2),2)
b

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [123]:
#Find the determinant
c= np.identity(3)
np.linalg.det(c)

1.0

##### Referenece docs (  https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)
#Determinant
#Trace
#Singular Vector Decomposition
#Eigen Values
#Matrix Norm
#Inverse
#Etc..


#### Statistics

In [124]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
np.min(stats)

1

In [126]:
np.max(stats, axis=1)

array([3, 6])

In [127]:
np.sum(stats, axis=0)

array([5, 7, 9])

###Reorganizing Arrays

In [132]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [135]:
#Veritically STacking Vectors
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
#horizontal stacks
h1= np.ones((2,4))
h2= np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous
Load Data from file

In [151]:
filedata = np.genfromtxt('Data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

#Boolean Masking and Advamced indexing

In [162]:
(~(filedata > 50) & (filedata < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [157]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [153]:
#You can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [187]:
import numpy as np
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],
                 [16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [189]:
arr1[2:4,0:2]
     

array([[11, 12],
       [16, 17]])

In [199]:
arr1[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [218]:
arr1[ [0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])